spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankcards
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
      #data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: RFNGTkNGRFNJblNETmNqc2RuY2puZGpzY25oakJEQ0hTZGNiZ2JzZGJjaGpiaGJIQkhCU0NESA==
    access: 3600000
    refresh: 2592000000
  pan:
    hmac-key: UhmkEmjnEvFFT26D
    aes-key: svW6Dx5v8CteQRc7
